### ISSUE TITLE
xlmns handling bug

### ISSUE THREAD

**Issue by MaRaSu** [dwayneparton/geojson-to-gpx#12]
GPX that is created has a bug, which is not bothering all parsers but some (e.g. Garmin Connect) which are more strict and refuse to parse it. The bug is because xlmns attribute is handled incorrectly and depending on browser (esp. Firefox) results in invalid GPX string after XML-serialization: either xlmns attribute is missing in gpx element and / or there is an extra xlmns="" attribute in other elements.

Ref old Firefox bug report that helped to find the root cause & fix: [Bugzilla: xlmns dropped](https://bugzilla.mozilla.org/show_bug.cgi?id=444085)

Fix (I can prepare PR later if desired):

```	
//const gpx = doc.createElement('gpx');
const gpx = createElementWithNS('gpx');
//gpx.setAttribute('xmlns', 'http://www.topografix.com/GPX/1/1');

function createElementWithNS(tagName: string): Element {
	return doc.createElementNS('http://www.topografix.com/GPX/1/1', tagName);
}
```

and replace all other occurrences of `doc.createElement()` in the code with `createElementWithNS()`.

**Comment by MaRaSu** [comment]
That was a quick PR! Thanks for creating this 0 dep gpx export library! When I run into this bug I first considered just switching to another library, but all of them seem to come with quite some dep issues or have been created for nodejs rather than browser.

**Comment by dwayneparton** [comment]
Awesome, glad to help! I was running into the exact same thing with dep issues.
Thanks again for taking the time to report. :)
