### ISSUE TITLE
Adaptation to node & React Native

### ISSUE THREAD

**Issue by MaRaSu** [dwayneparton/geojson-to-gpx#15]
Readme.md says "Designed to be a browser library...", however given the lack of deps and straightforward code I tried to adapt this lib to also my React Native app (using @xmldom/xmldom) and with a little modification it worked. Therefore should work also with Node.js.

What I had to do was to change just a few things:
- `...document.implementation.createDocument('http://www.topografix.com/GPX/1/1', '');`to allow for DI of the DOMImplementation (from xmldom or browser depending on the runtime env)
- Change 3 instances of `xxx.append()` to be `xxx.appendChild()`which xmldom supports. First change straightforward, the 2 latter in the form of `wpts.forEach((wpt) => gpx.appendChild(wpt));`

**Comment by dwayneparton** [comment]
@MaRaSu Just now seeing this. Thanks for sharing!

**Comment by dwayneparton** [comment]
> `...document.implementation.createDocument('http://www.topografix.com/GPX/1/1', '');`to allow for DI of the DOMImplementation (from xmldom or browser depending on the runtime env)

I'm not quite following what you meant here but with your updates you should be able to use `@xmldom/xmldom` if you set the global document to be `{implementation: new DOMImplementation()}`. Probably not the most ideal though. 

I updated `append` to be `appendChild` in #16 

Thanks again for the suggestions, super helpful.

**Comment by dwayneparton** [comment]
Also feel free to re-open it was auto closed by the PR. Happy to add this functionality
